### ISSUE TITLE
GitHub CI actions

### ISSUE THREAD

**Issue by HLRichardson-Git** [HLRichardson-Git/Gestalt#32]
I have never utilized any GitHub CI actions, but would love for this project to utilize then as I believe they are extremely helpful for maintainers.

I do not know the extent of how useful they could be, but I do currently have two ideas for actions I would like to see added:

- [ ] **1: Running unit tests**
- [ ] **2. Checking if all source files have our copyright header**

The first one to run the unit tests should not be difficult as we are using Google Test for our unit tests, which when we build the projcect using the `GESTALT_BUILD_TESTS` & `GESTALT_FETCH_GOOGLETEST` flags it should build our tests and then all we would have to do is run the executable, and check if they passed.

The second one seems a bit harder because we got a few questions to think of before we do it. First, can we specify for the script to only search in *.h and *.cpp (im sure we can), but then do we only check the files be updated in a PR for the header? Do we check all files? Would this mean we would have to change the year of the copyright for all files when its a new year so our action doesn't fail? I'm not sure.

**Comment by mirzaim** [comment]
Hi!
I’d like to work on setting up GitHub Actions for this.
Could you assign this issue to me?"

**Comment by HLRichardson-Git** [comment]
Yeah, I'd be happy too! This was the one I was honestly not sure where to start, so thanks for taking it on.

I may need some help in setting them up, outside of writing the scripts if you're up for that additional challenge lol.

**Comment by HLRichardson-Git** [comment]
Closing this issue. Great work on adding this to Gestalt!

mirzaim implemented this into branch `release/0.6.2` which will be included in the version release of Gestalt 0.6.2 (which I plan to release tomorrow 11/3). Now whenever a push or pr is made to main or a release branch the unit tests we implement will be ran. This will give maintainers and contributors more assurance that new additions are at least passing our unit tests.
